package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.engine.framework.GameDataManager

// Utility class with only static methods and constants in Java; no instance state.
Game_Data_Manager :: struct {}

