package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.engine.history.change.units.DamageUnitsHistoryChange

Damage_Units_History_Change :: struct {
	change:          ^Composite_Change,
	location:        ^Territory,
	damage_to_units: ^Integer_Map(^Unit),
}

