package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.triplea.ai.pro.logging.ProLogSettings

Pro_Log_Settings :: struct {
	log_history_limited: bool,
	log_history_limit:   int,
	log_enabled:         bool,
	log_level:           int,
}

