package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.triplea.ai.pro.data.ProOtherMoveOptions

Pro_Other_Move_Options :: struct {
	max_move_map: map[^Territory]^Pro_Territory,
	move_maps:    map[^Territory][dynamic]^Pro_Territory,
}

