package game

Trigger_Attachment :: struct {
	using abstract_trigger_attachment:  Abstract_Trigger_Attachment,
	frontier:                           ^Production_Frontier,
	production_rule:                    [dynamic]string,
	tech:                               [dynamic]^Tech_Advance,
	available_tech:                     map[string]map[^Tech_Advance]bool,
	placement:                          map[^Territory]^Integer_Map,
	remove_units:                       map[^Territory]^Integer_Map,
	purchase:                           ^Integer_Map,
	resource:                           string,
	resource_count:                     i32,
	support:                            map[string]bool,
	relationship_change:                [dynamic]string,
	victory:                            string,
	activate_trigger:                   [dynamic]^Tuple(string, string),
	change_ownership:                   [dynamic]string,
	unit_types:                         [dynamic]^Unit_Type,
	unit_attachment_name:               ^Tuple(string, string),
	unit_property:                      [dynamic]^Tuple(string, string),
	territories:                        [dynamic]^Territory,
	territory_attachment_name:          ^Tuple(string, string),
	territory_property:                 [dynamic]^Tuple(string, string),
	players:                            [dynamic]^Game_Player,
	player_attachment_name:             ^Tuple(string, string),
	player_property:                    [dynamic]^Tuple(string, string),
	relationship_types:                 [dynamic]^Relationship_Type,
	relationship_type_attachment_name:  ^Tuple(string, string),
	relationship_type_property:         [dynamic]^Tuple(string, string),
	territory_effects:                  [dynamic]^Territory_Effect,
	territory_effect_attachment_name:   ^Tuple(string, string),
	territory_effect_property:          [dynamic]^Tuple(string, string),
}

