package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.engine.display.IDisplay$NotifyRetreatMessage$NotifyRetreatMessageBuilder

Notify_Retreat_Message_Builder :: struct {
	short_message:          string,
	message:                string,
	step:                   string,
	retreating_player_name: string,
}
