package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.triplea.ai.pro.util.MoveBatcher

Move_Batcher :: struct {
	move_sequences: [dynamic][dynamic]^Move_Description,
}
