package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.engine.posted.game.pbem.PbemMessagePoster

Pbem_Message_Poster :: struct {
	game_properties:    ^Game_Properties,
	save_game_file:     string,
	turn_summary:       string,
	turn_summary_ref:   string,
	email_send_status:  string,
	current_player:     ^Game_Player,
	round_number:       int,
	game_name_and_info: string,
}

