package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.engine.message.RemoteMethodCall

Remote_Method_Call :: struct {
	remote_name:   string,
	method_name:   string,
	args:          []any,
	method_number: int,
	arg_types:     []string,
}
