package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.triplea.ai.pro.ProPoliticsAi

// Pro politics AI.
Pro_Politics_Ai :: struct {
	calc:     ^Pro_Odds_Calculator,
	pro_data: ^Pro_Data,
}

