package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.engine.framework.ui.DefaultGameChooserEntry

Default_Game_Chooser_Entry :: struct {
	installed_map: ^Installed_Map,
	game_name:     string,
}
