package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - games.strategy.engine.history.History

History :: struct {
	writer:            ^HistoryWriter,
	changes:           [dynamic]^Change,
	game_data:         ^GameData,
	panel:             ^HistoryPanel,
	next_change_index: int,
	seeking_enabled:   bool,
}

