package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - org.triplea.map.description.file.MapDescriptionYamlReader

// Utility class — no instance state.
Map_Description_Yaml_Reader :: struct {}
