package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - org.triplea.map.data.elements.Map$Connection

Map_Data_Connection :: struct {
	t1: string,
	t2: string,
}

