package game

// TODO: blank stub generated by triplea-port-bootstrap.
// One file per Java class. Replace this header when the
// class's structs and procs are fully ported.
// Java owners covered by this file:
//   - org.triplea.game.client.ui.swing.laf.SubstanceLookAndFeelManager

Substance_Look_And_Feel_Manager :: struct {}

