#!/usr/bin/env node
// orchestrator hook emitter — generated by VS Code extension. Do not edit.
import { appendFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const out = process.argv[2];
if (!out) { process.stdout.write('{}\n'); process.exit(0); }

let raw = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    mkdirSync(dirname(out), { recursive: true });
    const rec = { _receivedAt: Date.now(), _raw: raw };
    try { rec.payload = JSON.parse(raw); } catch { rec.payload = null; }
    appendFileSync(out, JSON.stringify(rec) + '\n');
  } catch {}
  process.stdout.write('{}\n');
});
// If stdin closes without data (some events), still exit cleanly.
setTimeout(() => { process.stdout.write('{}\n'); process.exit(0); }, 3000).unref();
