#!/usr/bin/env python3
"""capture_proc_snapshot.py — capture before/after snapshots for ONE Java method.

The Byte Buddy snapshot agent (templates/snapshot-agent/) instruments every
method listed in jfr-methods.txt with a tick counter and conditional GameData
+ params + return-value dumps. Filtering is via include.classes / include.methods
in snapshot.config. This script wraps the whole pipeline so you can drill into
ONE yellow proc with a single command:

    scripts/capture_proc_snapshot.py \\
        --class games.strategy.triplea.delegate.battle.MustFightBattle \\
        --method determineStepStrings \\
        [--triplea triplea] \\
        [--out triplea/conversion/odin_tests/dep_determine_step_strings/snapshots]

Pipeline:
  1. Ensure conversion/snapshot-agent/ is installed in the upstream checkout
     (call scripts/patch_triplea.py first if it isn't).
  2. Build the agent fat-jar via `./gradlew jar` (cached after first run).
  3. Write a one-off snapshot.config with the include filters set to JUST
     the requested class+method (any other instrumented call is tick-counted
     but not dumped).
  4. Invoke the smoke test (Ww2v5JacocoRun.runWithSnapshots) with
     -PsnapshotAgent=<jar> -Dsnapshot.outDir=<scratch> -Dsnapshot.config=<cfg>
  5. Walk the resulting tick-NNNNNNNNNN/ dirs, pick the ones whose
     before-meta.txt's `method` line matches our filter, and copy them into
     the per-proc snapshots/{NNNN}/ tree (before.json, after.json, meta.txt,
     return.txt) at the destination path.

Usage:
    scripts/capture_proc_snapshot.py --class FQCN --method NAME [--out DIR]
                                     [--triplea PATH] [--rounds N]
                                     [--keep-raw]

Idempotent — safe to re-run; per-call config is written to a temp file so
existing dumps under --out are overwritten.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent


def fail(msg: str) -> None:
    print(f"capture_proc_snapshot: {msg}", file=sys.stderr)
    sys.exit(1)


def derive_proc_dir_name(class_fqcn: str, method: str) -> str:
    """e.g. MustFightBattle + determineStepStrings -> dep_must_fight_battle_determine_step_strings"""
    cls_short = class_fqcn.rsplit(".", 1)[-1]
    snake = re.sub(r"(?<!^)(?=[A-Z])", "_", cls_short + "_" + method).lower()
    return f"dep_{snake}"


def write_per_call_config(triplea: Path, class_fqcn: str, method: str,
                           out_dir: Path) -> tuple[Path, Path]:
    """Materialise a snapshot.config + a narrowed methods file for this run.

    The agent installs Byte Buddy advice on EVERY method of EVERY class listed
    in the methods file. Listing all 1010 methods makes the instrumented game
    run ~50x slower. By narrowing the methods file to entries matching the
    target class only, the agent leaves all other classes at native speed.
    """
    agent_dir = triplea / "conversion" / "snapshot-agent"
    full_methods = agent_dir / "jfr-methods.txt"
    cls_short = class_fqcn.rsplit(".", 1)[-1]
    cls_path_prefix = class_fqcn.replace(".", "/")

    # Filter the master list down to lines that mention the target class.
    # Two recognised line shapes:
    #   games/strategy/.../ClassName.java:methodName(params)
    #   games/strategy/.../ClassName$Inner.java:methodName(params)
    # We keep both ClassName and ClassName$* for completeness.
    narrow = []
    for line in full_methods.read_text().splitlines():
        if not line.strip():
            continue
        if line.startswith(cls_path_prefix + ".java:") or line.startswith(cls_path_prefix + "$"):
            narrow.append(line)
    if not narrow:
        # Fall back to the full master list — at least the agent will work,
        # just slower. (Common when the requested class isn't in jfr-methods.txt.)
        narrow_path = full_methods
        print(f"[capture] no methods matched {cls_path_prefix} — using full list (slow)")
    else:
        narrow_path = out_dir / "methods.txt"
        narrow_path.write_text("\n".join(narrow) + "\n")
        print(f"[capture] narrowed methods file: {len(narrow)} entries from {cls_short}")

    cfg = out_dir / "snapshot.config"
    cfg.write_text(
        "# Auto-generated by scripts/capture_proc_snapshot.py — DO NOT EDIT\n"
        f"methods.file={narrow_path}\n"
        "snapshot.rangeStart=1\n"
        "snapshot.rangeEnd=50000000\n"
        f"snapshot.outDir={out_dir}\n"
        f"snapshot.include.classes={cls_short}\n"
        f"snapshot.include.methods={method}\n"
        "snapshot.exclude.classes=UnifiedInvocationHandler,PlayerBridge,UnifiedMessenger,EndPoint\n"
        "snapshot.saveGameData=true\n"
        "snapshot.saveParams=true\n"
        "snapshot.saveReturn=true\n"
    )
    return cfg, narrow_path


def build_agent_jar(triplea: Path) -> Path:
    """Build conversion/snapshot-agent/build/libs/snapshot-agent.jar (cached)."""
    agent_dir = triplea / "conversion" / "snapshot-agent"
    if not agent_dir.is_dir():
        fail(f"snapshot-agent not installed at {agent_dir}; run scripts/patch_triplea.py first")
    jar = agent_dir / "build" / "libs" / "snapshot-agent.jar"
    print(f"[capture] building agent jar (cached if up-to-date)...", flush=True)
    subprocess.check_call(
        [str(triplea / "gradlew"), "--no-daemon", "--quiet", "jar"],
        cwd=agent_dir,
    )
    if not jar.is_file():
        fail(f"agent jar missing after build: {jar}")
    return jar


def run_smoke_test(triplea: Path, agent_jar: Path, config: Path,
                   methods: Path, out_dir: Path, rounds: int | None,
                   max_bytes: int, max_minutes: float) -> None:
    cmd = [
        str(triplea / "gradlew"), "--no-daemon",
        ":game-app:smoke-testing:test",
        "--tests", "*Ww2v5JacocoRun.runWithSnapshots",
        "--rerun",
        f"-PsnapshotAgent={agent_jar}",
        f"-PsnapshotConfig={config}",
        f"-PsnapshotMethods={methods}",
        f"-Dsnapshot.outDir={out_dir}",
        f"-Dsnapshot.maxBytes={max_bytes}",
        f"-Dsnapshot.maxMillis={int(max_minutes * 60 * 1000)}",
        "-x", "jacocoTestReport",
    ]
    if rounds is not None:
        cmd.append(f"-Dsnapshot.rounds={rounds}")
    # Driver-side hard kill: agent's wall-clock cap is best-effort. We add a
    # 60-second grace and SIGKILL the gradle subprocess if it overruns. This
    # is the last line of defense against a runaway capture filling the disk.
    grace_secs = max_minutes * 60 + 60
    print(f"[capture] running smoke test (timeout {grace_secs:.0f}s, maxBytes={max_bytes})...", flush=True)
    try:
        subprocess.run(cmd, cwd=triplea, timeout=grace_secs, check=True)
    except subprocess.TimeoutExpired:
        fail(f"smoke test exceeded {max_minutes} min wall clock and was killed. "
             f"Raise --max-minutes if this proc legitimately needs more time. "
             f"Scratch dir under {out_dir} preserved for inspection.")


def parse_meta(meta_file: Path) -> dict:
    out = {}
    if not meta_file.is_file():
        return out
    for line in meta_file.read_text().splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            out[k.strip()] = v.strip()
    return out


def post_process(scratch_dir: Path, dest_dir: Path,
                 class_fqcn: str, method: str) -> int:
    """Walk tick-NNNNNNNNNN/ dirs, keep only ones for our target method,
    renumber 0001..NNNN, copy to dest_dir/<NNNN>/."""
    cls_short = class_fqcn.rsplit(".", 1)[-1]
    method_simple = method
    target_subdirs = sorted(p for p in scratch_dir.iterdir()
                              if p.is_dir() and p.name.startswith("tick-"))
    matched = []
    for td in target_subdirs:
        meta = parse_meta(td / "before-meta.txt")
        sig = meta.get("method", "")
        # Origin signature looks like "public void games.strategy....MustFightBattle.determineStepStrings()"
        if f".{cls_short}." in sig and f".{method_simple}(" in sig:
            matched.append(td)
    print(f"[capture] {len(matched)} tick-dirs match {cls_short}.{method_simple}")
    if not matched:
        return 0
    if dest_dir.exists():
        shutil.rmtree(dest_dir)
    dest_dir.mkdir(parents=True)
    for i, td in enumerate(matched, start=1):
        snap = dest_dir / f"{i:04d}"
        snap.mkdir()
        # Map agent dump filenames -> snap_runner-style names.
        for src_name, dst_name in (
            ("before-gamedata.json", "before.json"),
            ("after-gamedata.json",  "after.json"),
            ("before-meta.txt",      "before-meta.txt"),
            ("after-meta.txt",       "after-meta.txt"),
            ("after-return.json",    "after-return.json"),
        ):
            src = td / src_name
            if src.is_file():
                shutil.copyfile(src, snap / dst_name)
        # Copy every before-param-N.json the agent emitted (variable arity).
        for param_src in sorted(td.glob("before-param-*.json")):
            shutil.copyfile(param_src, snap / param_src.name)
        # Pull the `return: ...` line out of after-meta.txt for easy diffing.
        meta = parse_meta(td / "after-meta.txt")
        if "return" in meta:
            (snap / "return.txt").write_text(meta["return"] + "\n")
    return len(matched)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--class", dest="class_fqcn", required=True,
                    help="Fully-qualified Java class name (e.g. games.strategy....MustFightBattle)")
    ap.add_argument("--method", required=True,
                    help="Method name (no parens, no params). Substring matched within the class.")
    ap.add_argument("--triplea", default=os.environ.get("TRIPLEA_DIR", "triplea"),
                    help="Path to upstream TripleA checkout (default: ./triplea)")
    ap.add_argument("--out", default=None,
                    help="Destination snapshots dir (default: <triplea>/conversion/odin_tests/<dep_name>/snapshots)")
    ap.add_argument("--rounds", type=int, default=None,
                    help="Override SNAPSHOT_ROUNDS (default: 2). Larger = more chance to hit combat-phase procs.")
    ap.add_argument("--max-bytes", type=int, default=10 * 1024 * 1024,
                    help="Cap on total bytes written by the agent (default: 10 MiB). Override for big methods.")
    ap.add_argument("--max-minutes", type=float, default=10.0,
                    help="Wall-clock cap in minutes (default: 10). Driver SIGKILLs gradle 60s past this.")
    ap.add_argument("--keep-raw", action="store_true",
                    help="Don't delete the scratch tick-* dump dir after post-processing.")
    args = ap.parse_args()

    triplea = Path(args.triplea).resolve()
    if not triplea.is_dir():
        fail(f"triplea dir not found: {triplea}")

    proc_dir_name = derive_proc_dir_name(args.class_fqcn, args.method)
    if args.out:
        dest = Path(args.out).resolve()
    else:
        dest = triplea / "conversion" / "odin_tests" / proc_dir_name / "snapshots"

    print(f"[capture] target: {args.class_fqcn}.{args.method}")
    print(f"[capture] dest:   {dest}")

    agent_jar = build_agent_jar(triplea)

    scratch = Path(tempfile.mkdtemp(prefix="snap-", dir=triplea / "build"))
    print(f"[capture] scratch: {scratch}")
    try:
        cfg, methods = write_per_call_config(triplea, args.class_fqcn, args.method, scratch)
        run_smoke_test(triplea, agent_jar, cfg, methods, scratch, args.rounds,
                       args.max_bytes, args.max_minutes)
        # Surface the agent's CAP_EXCEEDED notice if present.
        cap_marker = scratch / "CAP_EXCEEDED.txt"
        if cap_marker.is_file():
            print(f"[capture] WARNING: {cap_marker.read_text().strip()}")
            print(f"[capture] Some captures may be missing. Re-run with larger --max-bytes / --max-minutes if needed.")
        n = post_process(scratch, dest, args.class_fqcn, args.method)
        if n == 0:
            fail("no tick-* dumps matched the filter — was the method actually entered?")
        print(f"[capture] wrote {n} snapshot(s) to {dest}")
    finally:
        if not args.keep_raw and scratch.exists():
            shutil.rmtree(scratch, ignore_errors=True)


if __name__ == "__main__":
    main()
