#!/usr/bin/env python3
"""generate_odin_stubs.py
================================================================================
Create one blank .odin file per row in the `methods` and `structs` tables.

Naming convention (the porter's flat layout):
  Java FQN dots and `$` -> `__`
  CamelCase class segments -> snake_case
  All entities owned by one Java class share a single .odin file
  (one file per class, not per method).

Files are written into ODIN_FLAT_DIR. The path is also written back to each
row's `odin_file_path` column so subsequent tooling agrees.

Each blank file is given a single TODO comment header so the file-level
implementation heuristic in update_db_paths.py picks it up as "not yet
implemented" until the developer/LLM removes the marker.

Usage:
    python3 generate_odin_stubs.py [--db PATH] [--out DIR]

Env vars:
    PORT_DB        sqlite database (default: ./port.sqlite)
    ODIN_FLAT_DIR  output directory (default: ./odin_flat)
================================================================================
"""

import argparse
import os
import re
import sqlite3
import sys
from pathlib import Path


def camel_to_snake(name: str) -> str:
    out: list[str] = []
    for i, c in enumerate(name):
        if c.isupper():
            prev = name[i - 1] if i > 0 else ""
            nxt = name[i + 1] if i + 1 < len(name) else ""
            if i > 0 and (prev.islower() or prev.isdigit()
                          or (prev.isupper() and nxt.islower())):
                out.append("_")
            out.append(c.lower())
        else:
            out.append(c)
    return "".join(out)


def fqn_to_filename(fqn: str) -> str:
    parts = re.split(r"[.$]", fqn)
    return "__".join(camel_to_snake(p) for p in parts if p) + ".odin"


def owner_fqn(primary_key: str) -> str:
    kind, body = primary_key.split(":", 1)
    if kind == "proc":
        return body.split("#", 1)[0]
    return body


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=os.environ.get("PORT_DB", "port.sqlite"))
    ap.add_argument("--out",
                    default=os.environ.get("ODIN_FLAT_DIR", "odin_flat"))
    args = ap.parse_args()

    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(args.db)
    cur = conn.cursor()

    # collect every primary_key from structs + methods
    keys: list[str] = []
    for table, col in (("structs", "struct_key"), ("methods", "method_key")):
        try:
            keys.extend(r[0] for r in cur.execute(f"SELECT {col} FROM {table}"))
        except sqlite3.OperationalError:
            pass

    # one file per owner class
    files_to_make: dict[str, set[str]] = {}
    for k in keys:
        fname = fqn_to_filename(owner_fqn(k))
        files_to_make.setdefault(fname, set()).add(k)

    written = 0
    skipped = 0
    for fname, owners in files_to_make.items():
        path = out_dir / fname
        if path.exists():
            skipped += 1
            continue
        owner_classes = sorted({owner_fqn(k) for k in owners})
        header = "// TODO: blank stub generated by triplea-port-bootstrap.\n" \
                 "// One file per Java class. Replace this header when the\n" \
                 "// class's structs and procs are fully ported.\n" \
                 f"// Java owners covered by this file:\n"
        body = "".join(f"//   - {c}\n" for c in owner_classes)
        path.write_text(f"package game\n\n{header}{body}\n")
        written += 1

    print(f"wrote {written} blank .odin files into {out_dir}")
    print(f"skipped (already exist): {skipped}")

    # update odin_file_path on every row so trackers agree on the canonical path
    updates_e: list[tuple[str, str]] = []
    updates_s: list[tuple[str, str]] = []
    updates_m: list[tuple[str, str]] = []
    for k in keys:
        full = str(out_dir / fqn_to_filename(owner_fqn(k)))
        updates_e.append((full, k))
        if k.startswith("struct:"):
            updates_s.append((full, k))
        elif k.startswith("proc:"):
            updates_m.append((full, k))

    cur.executemany(
        "UPDATE entities SET odin_file_path = ? WHERE primary_key = ?",
        updates_e,
    )
    cur.executemany(
        "UPDATE structs SET odin_file_path = ? WHERE struct_key = ?",
        updates_s,
    )
    cur.executemany(
        "UPDATE methods SET odin_file_path = ? WHERE method_key = ?",
        updates_m,
    )
    conn.commit()
    print(f"updated odin_file_path on {len(updates_e)} entities, "
          f"{len(updates_s)} structs, {len(updates_m)} methods")
    conn.close()


if __name__ == "__main__":
    main()
